The data is 45000x9 table. The output variable (loan_status) can have values 0 or 1.
The accuracy of sklearn model is 82.37777777777778%
The accuracy of other model is  78.11111111111111 %

In [15]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings( "ignore" )
from sklearn.linear_model import LogisticRegression

In [23]:
#importing data
file_path = 'ICGproject.csv'
loan_data = pd.read_csv(file_path)
loan_data.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [17]:
loan_data.info()
loan_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,8.031905e+04,5.410333,9583.157556,11.006606,0.139725,5.867489,632.608756,0.222222
std,6.045108,8.042250e+04,6.063532,6314.886691,2.978808,0.087212,3.879702,50.435865,0.415744
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.720400e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704800e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.578925e+04,8.000000,12237.250000,12.990000,0.190000,8.000000,670.000000,0.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000

In [24]:
#preprocessing
loan_data.dropna(inplace=True)
for i in loan_data.columns:
  if loan_data[i].dtype=="object":
    loan_data.drop(i,axis=1,inplace=True)
loan_data.info()
X = loan_data.iloc[:,:-1].values
Y = loan_data.iloc[:,-1:].values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  45000 non-null  float64
 1   person_income               45000 non-null  float64
 2   person_emp_exp              45000 non-null  int64
 3   loan_amnt                   45000 non-null  float64
 4   loan_int_rate               45000 non-null  float64
 5   loan_percent_income         45000 non-null  float64
 6   cb_person_cred_hist_length  45000 non-null  float64
 7   credit_score                45000 non-null  int64
 8   loan_status                 45000 non-null  int64
dtypes: float64(6), int64(3)
memory usage: 3.1 MB

In [26]:
# Split the data into training and testing sets

X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size = 0.1, random_state = 0 )

In [27]:
#using sklearn

#model training
model1 = LogisticRegression()
model1.fit( X_train, Y_train)

# Prediction on test set
Y_pred1 = model1.predict( X_test )

#measuring performance
correctly_classified1 = 0

 # counter
count = 0
for count in range( np.size( Y_pred1 ) ) :

  if Y_test[count] == Y_pred1[count] :
    correctly_classified1 = correctly_classified1 + 1

  count = count + 1

print( "Accuracy on test set by sklearn model   :  ", (  correctly_classified1 / count ) * 100 )

Accuracy on test set by sklearn model   :   82.37777777777778

In [29]:
#without using sklearn

class LogitRegression() :
  def __init__( self, learning_rate, iterations ) :
    self.learning_rate = learning_rate
    self.iterations = iterations

  # Function for model training
  def fit( self, X, Y ) :
    # no_of_training_examples, no_of_features
    self.m, self.n = X.shape
    # weight initialization
    self.W = np.zeros( self.n )
    self.b = 0
    self.X = X
    self.Y = Y

    # gradient descent learning

    for i in range( self.iterations ) :
        self.update_weights()
    return self

  # Helper function to update weights in gradient descent

  def update_weights( self ) :
      A = 1 / ( 1 + np.exp( - ( self.X.dot( self.W ) + self.b ) ) )

     # calculate gradients
      tmp = ( A - self.Y.T )
      tmp = np.reshape( tmp, self.m )
      dW = np.dot( self.X.T, tmp ) / self.m
      db = np.sum( tmp ) / self.m

      # update weights
      self.W = self.W - self.learning_rate * dW
      self.b = self.b - self.learning_rate * db

      return self

  # Hypothetical function  h( x )

  def predict( self, X ) :
      Z = 1 / ( 1 + np.exp( - ( X.dot( self.W ) + self.b ) ) )
      Y = np.where( Z > 0.5, 1, 0 )
      return Y

# Model training
model2 = LogitRegression( learning_rate = 0.01, iterations = 1000 )
model2.fit( X_train, Y_train )

# Prediction on test set
Y_pred2 = model2.predict( X_test )

#measure performance
correctly_classified2=0

# counter
count = 0
for count in range( np.size( Y_pred2 ) ) :

  if Y_test[count] == Y_pred2[count] :
    correctly_classified2 = correctly_classified2 + 1

  count = count + 1

print( "Accuracy on test set by model   :  ", (  correctly_classified2 / count ) * 100 )

Accuracy on test set by model   :   78.11111111111111